name: CI

on:
  pull_request:

jobs:
  ci-base:
    runs-on: ubuntu-latest
    environment: ci
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.18
    - name: Run Python commands
      run: |
        pip install --upgrade pip
        pip install poetry==1.6.1
    - name: Install dependencies
      run: |
        poetry install --with dev
    - name: Run checks
      run: |
        make checks
    - name: Run tests
      run: |
        make tests


  ci-semantic-release:
    runs-on: ubuntu-latest
    environment: ci-semantic-release
    needs: ci-base
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        commit: true
        metadata: false
        vcs_release: false
        github_token: ${{ secrets.GH_TOKEN }}
