name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-base:
    runs-on: ubuntu-latest
    environment: ci-base
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.18
    - name: Run Python commands
      run: |
        pip install --upgrade pip
        pip install poetry==1.6.1
    - name: Install dependencies
      run: |
        poetry install --with dev
    - name: Run checks
      run: |
        make checks
    - name: Run tests
      run: |
        make tests
