name: Dispatch Semantic Release

on:
  dispatch:
    types: [release]

jobs:
  disp-semantic-release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        commit: true
        vcs_release: false
        github_token: ${{ secrets.GH_TOKEN }}
