name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    concurrency: release
    needs: ci-base
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        git_committer_name: Xmaster6y
        git_committer_email: 66315201+Xmaster6y@users.noreply.github.com
        commit: true
        build_metadata: true
        vcs_release: true
        github_token: ${{ secrets.GH_TOKEN }}
